# Generated by Django 5.0.3 on 2024-03-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('major', models.CharField(default='', max_length=30)),
                ('github', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
