# Generated by Django 5.0.3 on 2024-03-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='post_id',
        ),
    ]
