# Generated by Django 5.0.3 on 2024-06-07 17:48

import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_thumnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgfile',
        ),
        migrations.AddField(
            model_name='post',
            name='thumnail_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[posts.validators.validate_image], verbose_name='썸네일'),
        ),
    ]
